spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${SPRING_APP_DATA_USERNAME}
    password: ${SPRING_APP_DATA_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  connection-timeout: 1m
  tomcat:
    max-swallow-size: 20MB
    accesslog:
      enabled: true
      directory: ${LOG_DIR}/tomcat_logs
      file-date-format: yyyy-MM-dd
      prefix: access_log
      suffix: .log
    basedir: ${TOMCAT_BASEDIR}
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: ${SSH_KEYSTORE}
    key-store-password: ${SSH_KEYSTORE_PASSWORD}
    key-alias: ${SSH_KEY_ALIAS}

custom:
  security:
    allowed-origins: http://localhost:3000 http://localhost:8080 http://127.0.0.1:8080

logging:
  level.com.example.demo: DEBUG
