spring:

  datasource:
    url: Invalid_URL
    username: ${SPRING_APP_DATA_USERNAME}
    password: ${SPRING_APP_DATA_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jndi.ignore: true

# TODO: Change audience

security.require-ssl: true

server:
  port: 443
  http.port: 80
  connection-timeout: 1m
  tomcat:
    max-swallow-size: 20MB
    accesslog:
      enabled: true
      directory: ${LOG_DIR}/tomcat_logs
      file-date-format: yyyy-MM-dd
      prefix: access_log
      suffix: .log
    basedir: ${TOMCAT_BASEDIR}
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: ${SSH_KEYSTORE}
    key-store-password: ${SSH_KEYSTORE_PASSWORD}
    key-alias: ${SSH_KEY_ALIAS}

custom.host.url: https://simplwork.com

